
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://172.23.16.144:3306/cloud_note?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://192.168.2.204:3306/cloud_note?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://192.168.150.134:3306/cloud_note?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://127.0.0.1:3306/cloud_note?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 129520
    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      initial-size: 5 #连接池初始化大小
#      min-idle: 10 #最小空闲连接数
#      max-active: 20 #最大连接数
#      web-stat-filter:
#        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
#      stat-view-servlet: #访问监控网页的登录用户名和密码
#        login-username: druid
#        login-password: druid
  redis:
    host: 127.0.0.1 # Redis服务器地址
#    host: 192.168.150.134 # Redis服务器地址
#    host: 192.168.2.204 # Redis服务器地址
#    host: 172.20.10.2 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
#    port: 7030 # Redis服务器连接端口
    port: 6379 # Redis服务器连接端口
    #password: redis129 # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）
#  # 静态文件路径映射
#  resources:
#    static-locations: file:/static
  #配置rabbitMq 服务器
  rabbitmq:
    host: 127.0.0.1
#    host: 192.168.150.128
    port: 5672
    username: guest
    password: guest
    #虚拟host 可以不设置,使用server默认host
#    virtual-host: JCcccHost
logging:
  level:
    root: info
    com.hyl.cloudnote: debug
#    org.jeecg.modules.hdx.mapper: debug

logstash:
  host: localhost
server:
  port: 8088

ueditor:
  image:
    filePath: /root/hyl/static/image/upload/ueditor/